### PR TITLE
add brooktardigradebroker.pas to brookrt.lpk

### PR DESCRIPTION
**Pull request by theavege**
Hi

I add brooktardigradebroker.pas to brookrt.lpk

Thanks

### CODE REVIEW

**Comment by silvioprog** [comment]
Hey @theavege, thanks for the patch! Hmmm since this is an RT package, though, we should avoid adding dependencies on external packages.

What do you think, @Al-Muhandis?

**Comment by Al-Muhandis** [comment]
> What do you think, @Al-Muhandis?

Despite the fact that I often use this broker unit, I think it's a bad idea to include it in `brookrt.lpk` because BrookFreePascal can work quite well without the new BrookFramework. 
On the other hand, it is inconvenient that we need to specify the exact path to this broker unit in the project. 
The third option is to create another lpk package for BrookFreePascal with support for BrookFramework. But it seems redundant to create another package for one broker unit. 
But it's definitely not worth adding, it seems to me

**Comment by theavege** [comment]
@Al-Muhandis [This](https://github.com/Al-Muhandis/taskworker) package for two units.

**Comment by Al-Muhandis** [comment]
> @Al-Muhandis [This](https://github.com/Al-Muhandis/taskworker) package for two units.

Yes. And even mainly for one unit. To make it easier to maintain and get rid of absolute paths in projects to units.

@theavege  Do you suggest creating another lpk here with the unit included? What do you think, @silvioprog ?

**Comment by theavege** [comment]
@Al-Muhandis @silvioprog I agree to the creation of a new package.

**Comment by silvioprog** [comment]
Hmmm I got the point. We're trying to add a broker unit for Tardigrade, but the main problem is that it adds a cross-dependency with its package. My point now is if we really need a new package, since it's just a broker unit.

I mean, maybe just a README file at the folder `~/brokers/Tardigrade` with some instructions to link Tardigrade package would be enough instead a new package.

What do you think guys? 🙂

**Comment by theavege** [comment]
@silvioprog I need any package with "..\brokers\Tardigrade\brooktardigradebroker.pas".

**Comment by silvioprog** [comment]
@theavege just curious. Which package name do you suggest?

**Comment by theavege** [comment]
@silvioprog brooktb.lpk

**Comment by silvioprog** [comment]
@theavege could you change the PR to create it? We can approve as soon as you send it. 🙂

**Comment by theavege** [comment]
@silvioprog I have done.

**Comment by silvioprog** [comment]
Thanks @theavege! Could you delete the file `packages/brooktb.pas`? It's generated automatically at build time, so we don't need to track it in the repo.

**Comment by theavege** [comment]
@silvioprog I have done.

**Review by silvioprog — APPROVED** [review]

**Comment by silvioprog** [comment]
Thanks a lot @theavege! Approved and merged. ✅

**Pull request merged**
